<?php

namespace ContainerR1UHUOk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaptchaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'captcha' shared service.
     *
     * @return \Captcha\Bundle\CaptchaBundle\Integration\BotDetectCaptcha
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'carlos-mg89'.\DIRECTORY_SEPARATOR.'symfony-captcha-bundle'.\DIRECTORY_SEPARATOR.'Integration'.\DIRECTORY_SEPARATOR.'BotDetectCaptcha.php';

        return $container->services['captcha'] = new \Captcha\Bundle\CaptchaBundle\Integration\BotDetectCaptcha($container);
    }
}
