<?php

namespace ContainerR1UHUOk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEwzRecaptcha_Validator_V3_TrueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'ewz_recaptcha.validator.v3.true' shared service.
     *
     * @return \EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrueValidatorV3
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'excelwebzone'.\DIRECTORY_SEPARATOR.'recaptcha-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'Constraints'.\DIRECTORY_SEPARATOR.'IsTrueValidatorV3.php';

        return $container->services['ewz_recaptcha.validator.v3.true'] = new \EWZ\Bundle\RecaptchaBundle\Validator\Constraints\IsTrueValidatorV3(false, 0.5, ($container->privates['ewz_recaptcha.recaptcha'] ?? $container->load('getEwzRecaptcha_RecaptchaService')), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));
    }
}
