<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Post extends \App\Entity\Post implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null],
        "\0".parent::class."\0".'contenuPub' => [parent::class, 'contenuPub', null],
        "\0".parent::class."\0".'datePub' => [parent::class, 'datePub', null],
        "\0".parent::class."\0".'dislikes' => [parent::class, 'dislikes', null],
        "\0".parent::class."\0".'file' => [parent::class, 'file', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'likes' => [parent::class, 'likes', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'comments' => [parent::class, 'comments', null],
        'contenuPub' => [parent::class, 'contenuPub', null],
        'datePub' => [parent::class, 'datePub', null],
        'dislikes' => [parent::class, 'dislikes', null],
        'file' => [parent::class, 'file', null],
        'id' => [parent::class, 'id', null],
        'likes' => [parent::class, 'likes', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
