<?php

namespace Container3OOvhyk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCaptchaHandlerControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Captcha\Bundle\CaptchaBundle\Controller\CaptchaHandlerController' shared autowired service.
     *
     * @return \Captcha\Bundle\CaptchaBundle\Controller\CaptchaHandlerController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'carlos-mg89'.\DIRECTORY_SEPARATOR.'symfony-captcha-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CaptchaHandlerController.php';

        $container->services['Captcha\\Bundle\\CaptchaBundle\\Controller\\CaptchaHandlerController'] = $instance = new \Captcha\Bundle\CaptchaBundle\Controller\CaptchaHandlerController();

        $instance->setContainer(($container->privates['.service_locator.mx0UMmY'] ?? $container->load('get_ServiceLocator_Mx0UMmYService'))->withContext('Captcha\\Bundle\\CaptchaBundle\\Controller\\CaptchaHandlerController', $container));

        return $instance;
    }
}
