<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXiwDizG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXiwDizG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXiwDizG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXiwDizG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXiwDizG\App_KernelDevDebugContainer([
    'container.build_hash' => 'XiwDizG',
    'container.build_id' => 'f9d65c93',
    'container.build_time' => 1708349095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXiwDizG');
