<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR1UHUOk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR1UHUOk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR1UHUOk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR1UHUOk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR1UHUOk\App_KernelDevDebugContainer([
    'container.build_hash' => 'R1UHUOk',
    'container.build_id' => '074069a6',
    'container.build_time' => 1709407577,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR1UHUOk');
