<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBkTEFTF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBkTEFTF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBkTEFTF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBkTEFTF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBkTEFTF\App_KernelDevDebugContainer([
    'container.build_hash' => 'BkTEFTF',
    'container.build_id' => 'edd1b7d7',
    'container.build_time' => 1707603647,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBkTEFTF');
